### ISSUE TITLE
Documentation for Assert and Check is mixed up

### ISSUE THREAD

**Issue by marco-m** [go-quicktest/qt#8]
Hello,

documentation for Assert:
> Assert checks that the provided argument passes the given check and calls tb.Error otherwise

documentation for Check:
> Check checks that the provided argument passes the given check and calls tb.Fatal otherwise

while Assert calls tb.Fatal and Check calls tb.Error. I think that the code is correct and the documentation is inverted?

**Comment by frankban** [comment]
Thanks for reporting! This is now fixed in `v0.1.0`.
